### ISSUE TITLE
System.Drawing.Common is not supported on non-Windows platforms

### ISSUE THREAD

**Issue by vese** [asposebarcode/Aspose_BarCode_NET#43]
Got this error running my app in docker
```
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
   at System.Drawing.LibraryResolver.EnsureRegistered()
   at System.Drawing.SafeNativeMethods.Gdip.PlatformInitialize()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipGetGenericFontFamilySansSerif(IntPtr& fontfamily)
   at System.Drawing.FontFamily.GetGdipGenericSansSerif()
   at System.Drawing.FontFamily.get_GenericSansSerif()
   at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at    . (Int32 , Int32 )
   at    .      (Int32 , Int32 , Int32 )
   at    .     (    , AutoSizeMode , Int32 )
   at    .     (    )
   at    . (BaseGenerationParameters )
   at    .()
   at    . (Stream , BarCodeImageFormat )
   at Aspose.BarCode.Generation.BarcodeGenerator.Save(Stream stream, BarCodeImageFormat format)
```
Could you migrate from System.Drawing.Common to another library as recommended in the link below?
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

**Comment by amjad-sahi** [comment]
We already logged a ticket with an id "BARCODENET-37915" for .NET 6.0 support and alternate of System.Drawing.Common. We decided to replace System.Drawing with Aspose.Drawing as system library (Aspose.Drawing image objects can be used to exchange data between user code and Aspose.Barcode code). However Aspose.Drawing has a lot of problems, so, at the moment, it is unusable. We work with Aspose.Drawing to solve the issues and add support of Aspose.Barcode on Xamarin.IOS, Xamarin.Android and .NET6 platforms. We may also consider Skia.Sharp and choose between Skia.Sharp and Aspose.Drawing. This was previously planned to 2022Q1, but due to complex issues and other problems, the .NET 6.0 support or solution could be shifted to more later date/time.

**Comment by amjad-sahi** [comment]
@vese,

We have switched to Aspose.Drawing implementation for non-Windows platforms. You may try our latest version/fix:
Aspose.BarCode for .NET v23.5 ([Releases](https://releases.aspose.com/barcode/net/) | [NuGet](https://www.nuget.org/packages/Aspose.BarCode/))
